# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quickies' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quickie
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport'
  ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'React/RCTNetwork', :path => '../node_modules/react-native'


  target 'QuickiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
