const quickieLookupHeaderMap = new Map();
quickieLookupHeaderMap.set('bs0000.All', 'All Quickies');
quickieLookupHeaderMap.set('bs0000.0', 'L0 Quickies');
quickieLookupHeaderMap.set('bs0000.1', 'L1 Quickies');
quickieLookupHeaderMap.set('bs0000.2', 'L2 Quickies');
quickieLookupHeaderMap.set('bs0000.3', 'L3 Quickies');
quickieLookupHeaderMap.set('bs0000.4', 'L4 Quickies');
quickieLookupHeaderMap.set('bs0000.5', 'L5 Quickies');
quickieLookupHeaderMap.set('bs0000.6', 'L6 Quickies');
quickieLookupHeaderMap.set('bs0001.All', 'Core Quickies');
quickieLookupHeaderMap.set('bs0001.0', 'L0 Core Quickies');
quickieLookupHeaderMap.set('bs0001.1', 'L1 Core Quickies');
quickieLookupHeaderMap.set('bs0001.2', 'L2 Core Quickies');
quickieLookupHeaderMap.set('bs0001.3', 'L3 Core Quickies');
quickieLookupHeaderMap.set('bs0001.4', 'L4 Core Quickies');
quickieLookupHeaderMap.set('bs0001.5', 'L5 Core Quickies');
quickieLookupHeaderMap.set('bs0001.6', 'L6 Core Quickies');
quickieLookupHeaderMap.set('bs0002.All', 'Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.0', 'L0 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.1', 'L1 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.2', 'L2 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.3', 'L3 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.4', 'L4 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.5', 'L5 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0002.6', 'L6 Lower Body Quickies');
quickieLookupHeaderMap.set('bs0003.All', 'Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.0', 'L0 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.1', 'L1 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.2', 'L2 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.3', 'L3 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.4', 'L4 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.5', 'L5 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0003.6', 'L6 Upper Body Quickies');
quickieLookupHeaderMap.set('bs0004.All', 'Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.0', 'L0 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.1', 'L1 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.2', 'L2 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.3', 'L3 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.4', 'L4 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.5', 'L5 Total Body Quickies');
quickieLookupHeaderMap.set('bs0004.6', 'L6 Total Body Quickies');

export { quickieLookupHeaderMap };
