const workoutLookupHeaderMap = new Map();
workoutLookupHeaderMap.set('bs0000.All', 'All Workouts');
workoutLookupHeaderMap.set('bs0000.1', 'L1 Workouts');
workoutLookupHeaderMap.set('bs0000.2', 'L2 Workouts');
workoutLookupHeaderMap.set('bs0000.3', 'L3 Workouts');
workoutLookupHeaderMap.set('bs0000.4', 'L4 Workouts');
workoutLookupHeaderMap.set('bs0000.5', 'L5 Workouts');
workoutLookupHeaderMap.set('bs0001.All', 'Core Workouts');
workoutLookupHeaderMap.set('bs0001.1', 'L1 Core Workouts');
workoutLookupHeaderMap.set('bs0001.2', 'L2 Core Workouts');
workoutLookupHeaderMap.set('bs0001.3', 'L3 Core Workouts');
workoutLookupHeaderMap.set('bs0001.4', 'L4 Core Workouts');
workoutLookupHeaderMap.set('bs0001.5', 'L5 Core Workouts');
workoutLookupHeaderMap.set('bs0002.All', 'Lower Body Workouts');
workoutLookupHeaderMap.set('bs0002.1', 'L1 Lower Body Workouts');
workoutLookupHeaderMap.set('bs0002.2', 'L2 Lower Body Workouts');
workoutLookupHeaderMap.set('bs0002.3', 'L3 Lower Body Workouts');
workoutLookupHeaderMap.set('bs0002.4', 'L4 Lower Body Workouts');
workoutLookupHeaderMap.set('bs0002.5', 'L5 Lower Body Workouts');
workoutLookupHeaderMap.set('bs0003.All', 'Upper Body Workouts');
workoutLookupHeaderMap.set('bs0003.1', 'L1 Upper Body Workouts');
workoutLookupHeaderMap.set('bs0003.2', 'L2 Upper Body Workouts');
workoutLookupHeaderMap.set('bs0003.3', 'L3 Upper Body Workouts');
workoutLookupHeaderMap.set('bs0003.4', 'L4 Upper Body Workouts');
workoutLookupHeaderMap.set('bs0003.5', 'L5 Upper Body Workouts');
workoutLookupHeaderMap.set('bs0004.All', 'Total Body Workouts');
workoutLookupHeaderMap.set('bs0004.1', 'L1 Total Body Workouts');
workoutLookupHeaderMap.set('bs0004.2', 'L2 Total Body Workouts');
workoutLookupHeaderMap.set('bs0004.3', 'L3 Total Body Workouts');
workoutLookupHeaderMap.set('bs0004.4', 'L4 Total Body Workouts');
workoutLookupHeaderMap.set('bs0004.5', 'L5 Total Body Workouts');

export { workoutLookupHeaderMap };
